apiVersion: v2
name: umbrella
description: An umbrella helm chart to deploy backend app and mongodb together
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: backend ## should match `name` in charts/subfolder `Chart.yaml`
    alias: backend
    charts: backend ## should match name of the subfolder in `charts`
    # repository: "file://../chartOne" ## does not work!
    version: "1.1.0" ## should match `version` in charts/subfolder `Chart.yaml`
    condition: backend.enabled
  - name: mongodb ## should match `name` in charts/subfolder `Chart.yaml`
    alias: mongodb
    charts: mongodb ## should match name of the subfolder in `charts`
    # repository: "file://../chartOne" ## does not work!
    version: "1.0.0" ## should match `version` in charts/subfolder `Chart.yaml`
    condition: mongodb.enabled
