apiVersion: v2
name: umbrella
description: An umbrella helm chart to deploy backend app and mongodb together
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: mongodb
    alias: mongodb
    charts: mongodb 
    version: "0.7.6"
    condition: mongodb.enabled
  - name: backend
    alias: backend
    charts: backend
    version: "1.1.0"
